# Generated by Django 4.2.13 on 2024-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_remove_customuser_username_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
